# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z7zXZ6uqAT2amfbqBeMyUzw-SInHudzO
"""

import pandas as pd
baza={
"FISH":["Yunusaliyev Behruzbek", "Murotjonov Begzod", "Muhammadov Azizbek", "Egamberdiyev Hamidullo"],
"Yoshi":["19","19","20","21"],
"Manzili":["Beshariq tumani","Beshariq tumani", "Beshariq tumani", "Beshariq tumani"],
"Jinsi":['erkak','erkak','erkak','erkak'],
"Oʻqish joyi":['TATUFF','TATUFF','FARDU','ADU']
}
db=pd.DataFrame(baza)
print(db)

filtr=db[db["Jinsi"]=='erkak']
print(filtr)

filtr=db[(db["Jinsi"]=='erkak')&(db["Oʻqish joyi"]=='TATUFF')&(db["Yoshi"]=="19")]
print(filtr)

